-- ============================================================================
-- SQL DDL Initialization Schema for QuizMaster (Oracle Database 23ai)
-- 
-- This script sets up the tables to store uploaded study materials
-- and their associated text chunks alongside their 768-dimensional 
-- vector embeddings generated by Google Gemini.
-- ============================================================================

-- 1. Drop existing tables if they exist (clean setup)
-- We wrap this in dynamic PL/SQL blocks so they execute without throwing errors 
-- if the tables do not exist yet.
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE document_chunks CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE study_materials CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- 2. Create STUDY_MATERIALS Table
-- Holds references to files uploaded by teachers or students.
CREATE TABLE study_materials (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename      VARCHAR2(255) NOT NULL,
    mime_type     VARCHAR2(100) NOT NULL,
    uploaded_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE study_materials IS 'Stores metadata for study materials (PDFs, Images, Text) uploaded by the users.';
COMMENT ON COLUMN study_materials.id IS 'Auto-incremented primary key.';
COMMENT ON COLUMN study_materials.filename IS 'Name of the uploaded file.';
COMMENT ON COLUMN study_materials.mime_type IS 'File type (e.g. application/pdf, image/png).';
COMMENT ON COLUMN study_materials.uploaded_at IS 'The timestamp when the file was uploaded.';


-- 3. Create DOCUMENT_CHUNKS Table
-- Holds individual chunks of extracted textbook text and their high-dimensional vector embeddings.
-- We use Oracle 23ai's native VECTOR data type.
CREATE TABLE document_chunks (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id   NUMBER NOT NULL,
    chunk_index   NUMBER NOT NULL,
    content       CLOB NOT NULL,
    embedding     VECTOR(768, FLOAT32) NOT NULL,
    page_number   NUMBER,
    CONSTRAINT fk_material FOREIGN KEY (material_id) REFERENCES study_materials(id) ON DELETE CASCADE
);

COMMENT ON TABLE document_chunks IS 'Stores partitioned text segments of study materials alongside their Gemini vector embeddings.';
COMMENT ON COLUMN document_chunks.id IS 'Auto-incremented primary key.';
COMMENT ON COLUMN document_chunks.material_id IS 'Foreign key referencing study_materials. Deleting a material deletes all its chunks.';
COMMENT ON COLUMN document_chunks.chunk_index IS 'The order index of the chunk in the document (0-based).';
COMMENT ON COLUMN document_chunks.content IS 'The actual string text content of the chunk.';
COMMENT ON COLUMN document_chunks.embedding IS 'Native vector storing 768-dimensional float32 embeddings from Gemini.';
COMMENT ON COLUMN document_chunks.page_number IS 'The page number inside the document this chunk was extracted from (useful for reference linking).';


-- 4. Create Vector Index (Recommended for Production-scale Datasets)
-- HNSW (Hierarchical Navigable Small World) index provides fast, approximate nearest neighbor search.
CREATE VECTOR INDEX chunk_vector_idx ON document_chunks (embedding)
ORGANIZATION IN_MEMORY_NEIGHBOR_GRAPH_HNSW;
